export const ROUTES = {
    BOTTOM_TAB_DASHBOARD: 'Home',
    HOME: 'DRAWER',
    COMMUNITY_HELP_REQUESTS: 'COMMUNITY_HELP_REQUESTS',
    CREATE_TASK_SCREEN: 'CREATE_TASK_SCREEN',
    EDIT_ADDRESS: 'EDIT_ADDRESS',
    EDIT_INTERESTS: 'EDIT_INTERESTS',
    EDIT_PERSONAL_DETAILS: 'EDIT_PERSONAL_DETAILS',
    EDIT_RADIUS_PREFERENCES: 'EDIT_RADIUS_PREFERENCES',
    FIND_FRIENDS_NEAR_BY_SCREEN: 'FIND_FRIENDS_NEAR_BY_SCREEN',
    FRIEND_PROFILE: 'FRIEND_PROFILE',
    HELP_AND_SUPPORT: 'HELP_AND_SUPPORT',
    INTRODUCE_FRIENDS_SCREEN: 'INTRODUCE_FRIENDS_SCREEN',
    MUTUALFRIENDS_SCREEN: 'MUTUALFRIENDS_SCREEN',
    MY_PROFILE: 'My Profile',
    OFFER_TO_HELP: 'OFFER_TO_HELP',
    PENDING_REQUESTS_SCREEN: 'PENDING_REQUESTS_SCREEN',
    SIGNIN_SCREEN: 'SIGNIN_SCREEN',
    SIGNUP_SCREEN: 'SIGNUP_SCREEN',
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    SUGGESTED_FRIENDS_SCREEN: 'SUGGESTED_FRIENDS_SCREEN',
    TASK_CREATED_SCREEN: 'TASK_CREATED_SCREEN',
    TASK_DETAILS: 'TASK_DETAILS',
    VERIFICATION_CODE_SCREEN: 'VERIFICATION_CODE_SCREEN',
    WEB_VIEW_SCREEN: 'WEB_VIEW_SCREEN',
    WHAT_AROUND_ME: 'WHAT_AROUND_ME',
    BOTTOM_TAB: {
        DAILY_MCQ: 'Daily MCQ',
        IMPORTANT: 'Important',
        NEWS: "News",
        TEST_SERIES: 'Test',
        VIDEO_SERIES: 'Video',
    },
    COMPLETE_PROFILE: {
        ADD_FRIENDS_SCREEN: 'ADD_FRIENDS_SCREEN',
        CONTACTS_LIST_SCREEN: 'CONTACTS_LIST_SCREEN',
        EXPLORE_NEIGHBORHOOD_SCREEN: 'EXPLORE_NEIGHBORHOOD_SCREEN',
        I_CAN_HELP_WITH_SCREEN: 'I_CAN_HELP_WITH_SCREEN',
        PERSONAL_DETAILS_SCREEN: 'PERSONAL_DETAILS_SCREEN',
    },
    IMPORTANT: {
        SUB_CATEGORY: 'Important Sub Categories',
        LIST: 'Important List',
        DETAIL: 'Important Detail'
    },
    NEWS: {
        SUB_CATEGORY: 'News Sub Categories',
        LIST: 'News List',
        DETAIL: 'News Detail'
    },
    TEST: {
        CATEGORY: 'Test Categories',
        LIST: 'Test List',
        PURCHASED_SERIES: 'Purchased Test Series',
        PURCHASED_TESTS: 'Purchased Tests',
        QUESTIONS: 'Questions',
        TEST_DETAIL: 'Test Detail'
    },
    VIDEO: {
        YOUTUBE_VIDEOS: 'Youtube Videos',
        SINGLE_VIDEO: 'Youtube Video',
    },
    DAILY_MCQ: {
        QUIZ_SCREEN: 'Quiz Screen'
    },
    MY_PURCHASE_HISTORY: 'My Purchase History',
}