export const TEXT_CONST = {
    //SIGN IN SCREEN
    DONT_HAVE_ACCOUNT: 'Don’t have an account? ',
    MOBILE_OR_EMAIL: 'Mobile number or email address',
    PASSWORD: 'Password',
    SIGNIN: 'Sign In',
    SIGNUP: 'Sign up',
    //SIGN UP SCREEN
    ALREADY_A_MEMBER: 'Already a member? ',
    ALREDY_MEMBER: 'Already a frugbi user. Please enter another',
    AND_AGREE: ' and agree to the ',
    DUPLICATE_PHONE: 'Duplicate phone number. Please enter another',
    EMAIL_ADDRESS: 'Email address',
    EMAIL_ALREADY_REGISTERED: 'This email is already registered with a different mobile number. Do you want to update the number?',
    FILL_CREDENTIALS: 'Please enter your credentials',
    INVALID_EMAIL: 'Invalid email address. Please verify and re-enter',
    INVALID_PASSWORD: 'Invalid Password, Please verify and re-enter',

    INVALID_PHONE: 'Invalid phone number. Please verify and re-enter',
    INVITATION_SENT: 'Invitation already sent. Please select another.',
    MOB_NUMBER: 'Mobile Number',
    PRIVACY_POLICY_TEXT: 'By continuing you acknowledge that you have read the ',
    PRIVACY_POLICY: 'Privacy Policy',
    SIGN_IN: 'Sign in',
    SIGN_UP: 'Sign Up',
    TERMS_OF_SERVICE: 'Terms of Service',
    UPDATE_MOBILE_NUMBER: 'Update mobile number',
    UPDATE: 'Update',
    VERIFICATION_TEXT: 'A verification email will be sent to the this address. Check your email and click on the link to confirm your address.',
    // VERIFICATION SCREEN
    CODE_NOT_RECEIVED: "Didn't receive the verification code?",
    CODE_RESEND: 'Code has been resent',
    INVALID_CODE: 'Invalid verification code',
    MOBILE_UPDATE_SUCESS: 'Mobile number updated successfully',
    REGISTRATION_SUCESS: 'Registration successful!',
    RESEND_CODE: 'Resend code',
    VERIFICATION_CODE_SUBTITLE: 'Verification code sent to ',
    VERIFICATION_CODE: 'Verification code',
    // PERSIONAL DETAILS SCREEN
    ADD_FRIEND: 'Add friend',
    ADD_FRIENDS: 'Add friends',
    ADDRESS_SUBTITLE: 'Your address helps us match you with helpers that are close by.',
    ADDRESS: 'Address',
    CHARACTERS: ' characters',
    CHOOSE_ATLEASE_THREE_TEXT: 'Choose at least 3 tasks you can help with',
    EDIT_CATEGORIES: 'Edit Categories',
    EDIT_HELP: 'Edit the categories I can help with',
    ENTER_ADDRESS: 'Enter Address',
    ENTER_FULL_NAME: 'Enter Full Name',
    EXPROLE_NEIGHBORHOOD: 'Explore Neighborhood',
    FULL_NAME: 'Full Name',
    GENDER: 'Gender',
    DENY: 'Deny',
    GENDER_TYPES: [
        {
            id: 1,
            label: 'Male'
        },
        {
            id: 2,
            label: 'Female'
        },
        {
            id: 3,
            label: 'Non binary'
        },
        {
            id: 4,
            label: 'Prefer not to say'
        },
    ],
    CONTACTS_PERMISSION_SUB_TITLE: 'Allow access to your contacts to invite your friends to frugbi',
    CONTACTS_PERMISSION_TITLE: 'Access to your contacts is required.',
    CONTACTS: 'Contacts',
    I_CAN_HELP_WITH: 'I can help with',
    I_DONT_HAVE_ONE: "I don't have one",
    INTERNET_ERROR: 'Your internet connection appears to be offline.',
    INVITATION_PENDING: 'Invitation pending',
    INVITE: 'Invite',
    NEIGHBORHOOD_BOTTOM_TEXT: 'Enter your neighborhood name/code and connect with frugbi users in your neighborhood!.',
    NEIGHBORHOOD_CODE_NAME: 'Neighborhood Code or Name',
    NEIGHBORHOOD_COUNT_USING: ' frugbi users in your neighborhood',
    NEIGHBORHOOD_WE_SUGGEST_TEXT: 'Please reach out to your HOA/Leasing office to get the code to see who is using frugbi around you.',
    PERSONAL_DETAILS: 'Personal Details',
    REFERRALS_TEXT: 'Referrals and Friend requests expand your community and give you a jump start in building a strong support system.',
    REQUEST_SENT: 'Request sent',
    STEP: 'Step',
    TAKE_PHOTO: 'Take photo',
    UPLOAD_FROM_PHONE: 'Upload from phone',
    UPLOAD_PROFILE_PICTURE: 'Update Profile Picture',

    //MENU Screen
    COINS: 'coins',
    FAQ: 'FAQs',
    HOURS: 'hours',
    LOGOUT: 'Logout',
    NOTIFICATIONS: 'Notifications',
    PROMOTIONS: 'Promotions',
    SUBSCRIPTIONS: 'Subscription',
    USER_AGREEMENT: 'User Agreement',
    VERSION: 'Version ',

    //Friends Screen
    ACCEPT: 'Accept',
    ALREADY_A_FRIEND: 'Already a friend',
    ADD: 'Add',
    CONFIRM_NEW_ADDRESS: 'Confirm New Address',
    CONFIRM_USER_ADDRESS: (displayName) => `I know ${displayName} who lives at this address.`,
    CONFIRM_USER_MOVED: (displayName) => `Do you want to confirm that ${displayName} moved?`,
    CONFIRM_VERIFICATION: 'Confirm Verification',
    CONFIRM_YOUR_NEW_ADDRESS: 'Confirm your most recent address',
    CONFIRM: 'Confirm',
    CHANGE_ADDRESS: 'Change Address',
    CURRENT_FRIENDS: 'Current Friends',
    ENTER_MOBILE_NUMBER: 'Enter mobile number',
    EXCHANGE_TASK_INFO_TEXT: 'Exchange task information with people nearby and find new friends',
    FIND_FRUGBI_FRIEND_NEARBY: 'Find new frugbi friends nearby',
    FRIEND_REQ_ACCEPTED: 'Friend Request is Accepted',
    FRIEND_REQ_DECLINE: 'Friend Request is Rejected',
    INVITATION_SENT_TO: (count) => `Invite sent to ${count} people`,
    INVITE_FRIEND_TO_FRUGBI: 'Invite friends to frugbi',
    INVITE_FRIENDS: 'Invite friends',
    IS_NOT_FRIEND: 'is no longer your friend',
    MILES_AWAY: ' miles away',
    _MUTUAL_FRIENDS: ' mutual friends',
    NO_FRIENDS_FOUND: 'No friends found',
    NO_FRIENDS_SUB_TEXT: 'Invite friends from your contact list to expand the frugbi community!',
    NO_FRIENDS_WITH_THIS_NAME: 'No friend found with this name',
    NO_FRIENDS_YET: 'No Friends Yet',
    NO_USER_FOUND_WITH_THIS_NAME: 'No user found with this name',
    NO_USER_FOUND: 'No User Found',
    NO_DATA_FOUND: 'No Data Found',
    PENDING_REQUESTS: 'Pending Requests ',
    PULL_TO_REFRESH: 'Pull to refresh',
    RECIPIENT: 'Recipient',
    SEARCH: "Search",
    SUGGESTED_FRIENDS: 'Suggested Friends',
    VERIFICATION_REQUEST_SENT: 'Verification request sent.',
    REPORTED_SUCCESSFULLY: 'Reported successfully.',
    VERIFIED_YOU: 'Verified you',
    VERIFY: 'Verify',
    VIEW_ALL: 'View All',
    YES: 'Yes',
    NO: 'No',
    YOU_HAVE_MOVED: ' friend(s) reported that you have moved.',
    FIND_FRIENDS_FILTERS: [{
        label: 'Distance',
        key: 'D'
    },
    {
        label: 'Acquaintance',
        key: 'A'
    },
    {
        label: 'Neighborhood',
        key: 'N'
    }],
    CURRENT_FRIENDS_FILTERS: [
        {
            label: 'All',
            id: 'A'
        },
        {
            label: 'Favourite',
            id: 'F'
        },
        {
            label: 'Helped',
            id: 'H'
        }
    ],

    //HOME SCREEN
    ACCEPT_PENDING_REQ: 'Please accept pending requests quickly to help people and grow our frugbi community..',
    HELP_I_NEED: 'Help I need',
    HELP_I_PROVIDING: 'Help I’m providing',
    HELP_NEED_SUB1: 'Please use the ',
    HELP_NEED_SUB2: ' button to get started on a task you would like to complete...',
    NO_UPCOMMING_TASK: 'No Upcoming Tasks',

    //MENU SCREEN
    CANCEL: 'Cancel',
    YOU_WANT_TO_LOGOUT: 'Are you sure you want to logout?',

    //PREFERENCES
    PREFERENCES_ITEMS: [
        {
            label: 'Auto-confirm requests from friends',
            key: 'autoconfirm_my_friends'
        },
        {
            label: 'Auto-confirm requests from favourites',
            key: 'autoconfirm_my_favorites'
        },
        {
            label: 'Auto-confirm requests from neighborhood',
            key: 'autoconfirm_my_neighborhood'
        },
    ],

    //COMPLETE PROFILE CONTACTS
    NO_CONTACTS_FOUND_NAME: 'No contact found with this name. Please try with other name.',
    NO_CONTACTS_FOUND: 'No Contact Found',

    //MY PROFILE
    ADD_INTERESTS: 'Add interests',
    ADD_SOME_INTERESTS: 'Add interests to connect to like-minded people.',
    CAN_HELP_WITH: 'Can Help with',
    CANCELED: 'Cancelled',
    EMAIL: 'Email',
    HELPED_ME: 'Helped Others',
    INTERESTS: 'Interests',
    MUTUAL_FRIENDS: 'Mutual Friends',
    MY_PROFILE: 'My Profile',
    NAME: 'Name',
    NEIGHBORHOOD_NAME: 'Neighborhood Name',
    NO_INTERESTS: 'No Interests',
    PROFILE_PIC_SUCESS: 'Profile picture uploaded successfully',
    TOOK_HELP: 'Help Taken',
    VERIFIED: 'verified',
    VERIFY_EMAIL_SUCESS: 'Verification link sent to your email address.',
    VERIFY_EMAIL: 'Verify Email',

    //Edit Personal Details
    EDIT_PERSONAL_DETAILS: 'Edit Personal Details',
    ENTER_EMAIL: 'Enter Email',
    ENTER_NEIGHBORHOOD_NAME: 'Enter Neighborhood Name',
    SAVE_CHANGES: 'Save changes',
    INVALID_NAME: 'Invalid Name',

    //Edit Address
    CITY: 'City',
    EDIT_ADDRESS: 'Edit Address',
    ENTER_CITY: 'Enter City',
    ENTER_STATAE: 'Enter State',
    ENTER_STREET: 'Enter Street',
    ENTER_ZIPCODE: 'Enter Zipcode',
    INVALID_CITY: 'Invalid City',
    INVALID_NEIGHBORHOOD_NAME: 'Invalid Neighborhood Name',
    INVALID_STATE: 'Invalid State',
    INVALID_STREEET: 'Invalid Street',
    INVALID_ZIPCODE: 'Invalid Zipcode',
    STATAE: 'State',
    STREET: 'Street',
    ZIPCODE: 'Zipcode',

    //Edit Interests
    CHOOSE_INTEREST_HEADER: 'Choose your interests',
    EDIT_INTERESTS: 'Edit Interests',

    //CREATE TASK
    DATE_TIME: 'Date and Time',
    HELP_REQUESTED: 'Help required at:',
    HELP_DELIVERED: 'Other Address (optional):',
    ADD_DELIVERY_INSTRUCTIONS: 'Additional Information if any:',
    I_NEED_HELP_WITH: 'I need help with',
    NEXT: 'Next',
    ADD_NEW_ADDRESS: 'Add New Address',
    SAVE_ADDRESS: 'Save Address',
    PICK_A_TASK: 'Pick a task you need help with',
    POST_REQUEST: 'Create Task',
    ADDRESS_NAME: 'Save As',
    ENTER_ADDRESS_NAME: `e.g.: Dad's Place, John's Place`,
    REMOVE_AS_FRIEND: 'Remove as Friend',
    REPORT_FRIEND_HAS_MOVED: 'Report Friend has moved',
    REQUEST_TO_VERIFY_ME: 'Request to verify me',
    SEEK_REQ_FORM: 'Seek Request from',
    PEOPLE_REQUIRED: 'People required',
    INVALID_DATE_TIME: 'Selected time must greater than current time',
    MINUTES_FOR_EACH_HELPER: 'Minutes requested from each helper',
    SEND_THIS_TASK_ONLY_TO_FRIENDS: 'Send this task only to friends',
    SEARCH_WITHIN: (miles = 0) => `Search within ${miles} mile(s) of my home location`,
    BASIC_PREFERENCES: `Basic Preferences`,
    MATCH_DISTANCE_RADIUS: 'Match Distance Radius',
    FRIEND_DISTANCE_RADIUS: 'Friend Distance Radius',
    HOW_TO_EARN_HELP_HOURS: 'How do you earn “Help” hours?',
    HOW_TO_EARN_COINS: 'How do you earn coins?',
    BORROW_HRS_TEXT: 'Good News! frugbi allows you to borrow up to 3 hours from the community. You are encouraged to pay back by helping someone.',
    USE_COINS_TEXT: (coins) => `Good News! frugbi allows you to borrow up to 3 hours from the community and will use your ${coins} coins to make up additional difference; You are encouraged to pay back to community by helping someone.`,
    REDUCE_TIME_TEXT: 'Reduce the task time because you don’t have enough time balance and/or coins.',
    GO_TO_HOME: 'Go to home',
    AUTO_APP_TEXT: 'Auto approve help from your friends & favorites?',
    TASK_CREATED_NOTE: 'NOTE: Please confirm as soon as they accept the help, to avoid losing help requests.',
    TASK_CREATED_COUNT: (count = 0) => `Frugbi has sent request to ${count} helpers.`,


    //HOME
    IM_INTERESTED: 'I’m interested',
    ADD_CATEGORY: 'Add category',
    COMUNITY_NEED_HELP: 'Community needs help with.',
    WHATS_GOING_AROUND: 'What’s going on around me?',
    COMUNITY_HELP_REQUEST: 'Community Help Requests',
    READY_TO_GO: 'Ready to go',
    FINDING_MATCHES: 'Finding matches',
    CONFIRM_YOUR_MATCHES: 'Confirm your matches',
    CANCELED: 'Canceled',
    INTEREST_ADDED_SUCCESS_MSG: 'This help request is added in your match making.',
    CATEGORY_ADDED_SUCCESS_MSG: '[CATEGORY] added to categories ‘I can help with’',


    //TASK DETAILS
    TASK_DETAILS: 'Task Details',
    SERVICE_ADDRESS: 'Service address',
    DELIVERY_ADDRESS: 'Delivery address',
    CANCEL_TASK: 'Cancel Task',
    CANCEL_OFFER_TITLE: 'Cancel Offer to Help',
    POTENTIAL_MATCHES: (active = 0, total = 0) => `Potential Matches (${active}/${total})`,
    REJECT: 'Reject',
    DISMISS: 'Dismiss',
    REMOVE: 'Remove',
    AWAITING_APPROVAL: 'Awaiting Approval',
    ACCEPT_TO_HELP: 'Offer Accepted',
    CANCEL_OFFER: 'Cancel Offer',
    CONFIRMED_HELPER: (active = 0, total = 0) => `Confirmed Helpers (${active}/${total})`,
    CANCEL_TASK_ALERT_MSG: 'Are you sure you want to cancel the task ',
    CANCEL_OFFER_ALERT_MSG: 'Are you sure you want to cancel help for task ',
    OFFER_TO_HELP_SENT: (name) => `Offer to help has been sent to ${name}.`,
    OFFER_TO_HELP_AUTO_ACCEPTED: (name) => `Your offer to help has been auto-accepted by ${name}`,
    AUTO_REQUEST_SUBHEADING: 'Any requests that match this time have been removed from your list',
    CANCEL_TASK_ALERT_MAKEUP: ' Make up?',
    YES_CANCEL: 'Yes, cancel',
    NO_LONGER_AVAIL: 'No longer available',
    PLEASE_CONFIRM_YOUR_HELPER: 'Please confirm your helpers quickly to ensure their availability',

    //Help and Support
    HELP_AND_SUPPORT: 'Help and Support',

    //Offer To Help
    OFFER_TO_HELP: (from, total) => `Offer to Help (${from}/${total})`,
    OFFER_HELP: 'Offer to help',
    TASK_FILTER_TITLE: (from, total) => `Task (${from}/${total})`,
    APPLY: 'Apply',
    OTHER_FILTER_TITLE: (selected) => `Other (${selected})`,
    LIMIT_TO_NEIGHBORHOOD: 'Limit to requests only within neighborhood',
    LIMIT_TO_FRIENDS: 'Limit to requests made by friends',
    LIMIT_TO_CONTACTS: 'Limit to requests made by new contacts',
    LIMIT_TO_PEOPLE_WORKED: 'Limit to requests to people I have worked with',
    NO_OFFER_TO_HELP_FOUND: 'No Offer To Help Found',

    //Activity Detail
    REQUEST_CHECK_IN: 'Request Check-in',
    REQUEST_CHECK_OUT: 'Request Check-out',
    CONTENUE: 'Continue',
    SHARE_CODE_WITH_REQ: 'Please share your verification code with the requestor',
    CHECKOUT_CODE_IS: 'Checkout verification code is',
    HOUR_OF_WORK: 'Hours of work calculated',
    PLEASE_ENTER_CODE: 'Please enter the verification code given by ',
    HOURS_CONSUMED: (hours = '') => `You have taken help for : ${hours}`,
    ADJUST_AS_NEEDED: 'Adjust time down as needed',
    SEND_TO_HELPER: 'Send to helper',
    VERIFY_LATER: 'Verify Later',
    I_KNOW_AND_LIVES: (displayName) => `I know ${displayName} and lives in this address.`,
    PENDING_CHECKOUT: 'Pending Checkout',
    TASK_COMPLETED: 'Task Completed',
    FEEDBACK: 'Feedback',
    SUBMIT: 'Submit',
    //new strings
    NAME_INPUT_NAME: 'name',
    EMAIL_INPUT_NAME: 'email',
    PASSWORD_INPUT_NAME: 'password',
    MOBILE_INPUT_NAME: 'mobile',
    CONFIRM_PASSWORD_INPUT_NAME: 'confirm_password',
    NAME_REQUIRED: 'Please enter your name',
    PHONE_REQUIRED: 'Please enter phone number',
    EMAIL_REQUIRED: 'Please enter an email',
    EMAIL_INVALID: 'Please enter a valid email',
    PASSWORD_REQUIRED: 'Please enter a password',
    CONFIRM_PASSWORD_REQUIRED: 'Please confirm your password',
    PASSWORD_DONT_MATCH: 'Passwords don\'t match',
    EMAIL_REGEX: /^(([^<>()\]\\.,;:\s@"]+(\.[^<>()\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    LOGIN_SUCCESS: 'Login successful!',
    ALL_TEST_SERIES: 'All Test Series',
    PURCHASED_TEST_SERIES: 'Purchased Test Series',
    TIME_LEFT: 'Time Left',
    START_TEST: 'Start Test',
    START_DAILY_QUIZ: 'Start Daily Quiz',
    DONE: 'Done',
    RATE_US: 'Rate Us',
    SHARE_APP: 'Share App',
    LOGOUT_ALERT: 'Are you sure you want to logout',
    MY_PURCHASE_HISTORY: 'My Purchase History',
    PURCHASED_TESTS: 'Purchased Tests',
    TEST_SERIES_CATEGORIES: 'Test Series Categories',
    TEST_SERIES: 'Test Series',
    TEST_SERIES_LIST: 'Test Series List',
    PURCHASED_TEST_SERIES_LIST: 'Purchased Test Series List'
}


export const LINKS = {
    EULA: 'https://www.termsfeed.com/live/f541004e-0b2d-41e6-93e9-e1d558296145',
    PRIVACY_POLICY: 'https://www.termsfeed.com/live/12a3431d-93ab-4b1f-9dff-68cb987066dd',
    TERMS_OF_SERVICE: 'https://www.termsfeed.com/live/6ee29195-8103-4de5-a3ed-3d2858031e68',
}